### PR TITLE
addresses #22

### PR DESCRIPTION
**Pull request by gzine**
Relates to #22
Fixes #22 

## Proposed Changes

  -- Edited "About this page" section
 @luisFilipePT

### CODE REVIEW

**Review by luisFilipePT — APPROVED** [review]
Nice, thanks 😀

**Comment by luisFilipePT** [comment]
There's conflicts on the branch, please rebase or merge and update the PR. 🙏

**Comment by gzine** [comment]
I have resolved the conflicts.  Is anything else needed?

**Review by luisFilipePT — APPROVED** [review]
Nothing else needed, thanks

**Pull request merged**
