### PR TITLE
Twitter share icon v1

### PR DESCRIPTION
**Pull request by lawrence-dass**
## Screenshots (if visual changes)
Twitter share Icon Top

The twitter site will open in a new tab, to ensure not lose the user engagement with our site.
Followed best practice, https://developers.google.com/web/tools/lighthouse/audits/noopener

I kept the design as per issue screenshot provided, please let me know if any adjustment to be done.

### CODE REVIEW

**Comment by luisFilipePT** [comment]
@Lawrence4code - Hey, nice work however (my bad 😊 ) the provided design was just a rough example.

I'm by no  means a designer but maybe we should drop that background color and use the simple a grey and when we hover it maybe grow a bit and turn blue.

Can you do it?

In a v2 version (or now 😄 ) we probably change to write and send the tweet action with a nice message, some hashtags and a link to the site.
You can check here an example:
http://twitter.com/share?text=Im Sharing on Twitter&url=https://stackoverflow.com/users/2943186/youssef-subehi&hashtags=stackoverflow,example,youssefusf

Any questions feel free and apologise the miscommunication 🙏

**Review by luisFilipePT — APPROVED** [review]
Super 💯

**Comment by luisFilipePT** [comment]
@all-contributors please add @Lawrence4code for code

**Comment by lawrence-dass** [comment]
Hey Luis, thanks for the feedback. I appreciate your prompt response.
I expected some changes to my PR, so nothing to apologize for.
Thanks for the opportunity and also making me aware of pre-commit hooks which is awesome, almost like magic.
Also, I like the intention of your project. If any issue with CSS, JS, React, or UI related issues, please feel free to assign to me, I'd be happy to contribute in anyway I can.

I love the way you maintain your codebase and project automation process. All the best, Godspeed :)

**Comment by luisFilipePT** [comment]
@Lawrence4code no problem, I will be adding issues/features in the days to come, theres a lot to be done 😄 , whenever you see an issue that pleases you and no commented to claim it feel free to add a claim comment and tag me, so that I can be faster assigning it to you.

Thanks

**Pull request merged**
