### PR TITLE
The suggested UI changes at DateTimeFormat page

### PR DESCRIPTION
**Pull request by triartleet**
https://github.com/xgeekshq/js-intl-kitchen-sink/issues/89

crop2

@luisFilipePT

### CODE REVIEW

**Comment by triartleet** [comment]
The colons were removed from the `<Form.Item />` because they do not appear on the same line with my "`<PopoverContent />`". 

Some info regarding this issue:
When antd's `<Form.Item />` is given a _label_ prop (can be a custom component), it wraps it with an html label element. The colons are rendered as `::after` of this label. 

I have no control on the styling of the label that antd creates. Everything could be resolved if I could change it to flex.

**update**: I will try passing a className like .formItem > label and see how it goes today, then update.

**Review by luisFilipePT — COMMENTED** [review]
Looks good but why not use the icons that we already have? 🤔 

https://ant.design/components/icon/

And please resolve the conflicts 😄

**Comment by triartleet** [comment]
> conflicts

Oh, did not know antd comes packed with its icons. Ye, I will update tonight. Cheers!

**Comment by triartleet** [comment]
Updated MR 
crop3.

Could you also tell me why the MR has not a clean diff :O ? I merged upstream.

**Review by luisFilipePT — APPROVED** [review]

**Pull request merged**
